### ISSUE TITLE
Table like structure renders weirdly in 1.0.26

### ISSUE THREAD

**Issue by keresztg** [KlausSchaefers/vue-low-code#35]
Hi!

I have a table like structure utilizing auto-layout and fill-container:
![image](https://user-images.githubusercontent.com/43315663/136089138-5344d38a-77eb-451a-8b05-c05b5a81e280.png)

Source: [TableBug.fig.zip](https://github.com/KlausSchaefers/vue-low-code/files/7288689/TableBug.fig.zip)

In the browser this renders with vue-low-code like this:
![image](https://user-images.githubusercontent.com/43315663/136089566-36a1617e-7d31-471b-ba3f-ae768cf3a39f.png)

Also resizing the frame results in different behavior in Figma and the browser.

What am I doing wrong?

Thanks,
Gábor

Ps.: The frame _cp.upload.list_ will be a Smart Container/Repeat Children that's why it has an additional element frame.

**Comment by KlausSchaefers** [comment]
Hi,

the issue is that in row, two of the columns do not have a fixed width, they are set to "fill" aka grow. The browser does now somehow try to determine the optimal distribution between the two "fill", but individual for each row. Therefore, the size of these columns might be different per row. This causes the effect that you see. To get a stable table design, you need to fix one additional columns, e.g. the right one.
![TableBug-–-Figma](https://user-images.githubusercontent.com/7108416/136096706-f141b2ca-348a-4142-b2fd-4c5f68de2e2d.png)

**Comment by keresztg** [comment]
So, is this a limitation of the browsers?
Hmmm, wondering how did Figma solve the problem of multiple "fill-container" elements in a single row... Using canvas and some JS magic? 🤔
