### ISSUE TITLE
(paging component) in actual use, when the number of pages is less than 3, 3 pages still appear

### ISSUE THREAD

**Issue by huangbaihei** [KlausSchaefers/vue-low-code#38]
look forward to your reply

**Comment by KlausSchaefers** [comment]
Can you update to 1.0.31

```
npm install vue-low-code@1.0.31
```

**Comment by huangbaihei** [comment]
Thank you for your reply! But when I upgraded to 1.0.32, I encountered two errors
![image](https://user-images.githubusercontent.com/37474464/139633128-c2a107be-851b-4dff-8b00-0f5261355ea2.png)

**Comment by KlausSchaefers** [comment]
Wow, there must have been something wrong with the build. Can you try

```
npm install vue-low-code@1.0.34
```

**Comment by huangbaihei** [comment]
Hi!  After upgrading to "1.0.34", there is still an error. And the callback when the screen is loaded is not executed.
![image](https://user-images.githubusercontent.com/37474464/139773080-1d79ba62-962a-41e6-98e2-f3e40c744ab4.png)

**Comment by KlausSchaefers** [comment]
Hi,

I think I found the issue. Could you try

```
npm install vue-low-code@1.0.34
```

Sorry for the trouble. I am porting to VUE3 and keeping both code bases causes some issues. The error message is shown because I am "rebranding" the package in the scope of the move to Vue3. Soon it will be called "Luisa". 

a) You can fix this issue by changing the **:app** property to **:design**

b) You can already move to Luisa:

If you want to start using Luisa, do the following:

```
npm install luisa-vue@2.0.6
```

You need to change the code to 


```
<template>
  <div class="home">
    <Luisa design="a2aa10atOYDU8XLBz2n3pTiJEjCsyY728M5hyCAD6UC8c7pDeyDkPpMAYC26" v-model="viewModel" :config="config"/>
  </div>
</template>
<style lang="scss">

</style>

<script>
import Vue from "vue";
import Luisa from 'luisa-vue'
Vue.use(Luisa);
```

**Comment by KlausSchaefers** [comment]
You can also customise how the paging is rendered now. Select the paging element. In the properties panel is a new drop down. 
![Pagging_Align](https://user-images.githubusercontent.com/7108416/140093593-30fa9a76-4fce-4f8e-84fe-7fd430d566d5.png)
.
