### ISSUE TITLE
Need help with Dropdown *Urgent

### ISSUE THREAD

**Issue by fahad-islam** [KlausSchaefers/vue-low-code#54]
Hi, Liquid Concession needs your help with Figma data-binding!

We are using your Figma plugin *( Figma Low Code ). 

We need your help with the Figma plugin feature that you guys build.

We want to use your plugin but the documentation is lacking a lot of features.

Could you help us out in figuring out a way to move forward?

Right now, We are using mui mantis theme for our Figma design

The design is ready but data binding is required.

Would love to connect and hear more from you guys as quickly as possible

regards,
Muhammad Fahad Islam.

Email: muhammadf@liquidconcessions.com
Twitter: https://www.twitter.com/_fahadislam
Github: @fahad-islam

**Comment by KlausSchaefers** [comment]
Hi,

there is a bug in the plugin. Let me try to fix it.

**Comment by fahad-islam** [comment]
Thank you so much @KlausSchaefers, Can we have a short meeting?

**Comment by fahad-islam** [comment]
![Screenshot from 2022-10-27 09-50-22](https://user-images.githubusercontent.com/89579421/198194785-956538b2-0bed-464e-858e-62083a5e5b8a.png)

Still facing this issue, What kind of updates do I need to make to get the updated version?
![Screenshot from 2022-10-27 09-52-11](https://user-images.githubusercontent.com/89579421/198194973-99c6b788-901b-4608-b31c-4e4379d4a6c6.png)

From Home.vue
![Screenshot from 2022-10-27 09-53-29](https://user-images.githubusercontent.com/89579421/198195146-8d6583a5-bae8-42f6-a043-eed78afcfa9b.png)

**Comment by KlausSchaefers** [comment]
This error happens when there are no options. Can you check:

a) The dropdown has the "options" data bin dinging set to dropdownOptions?

b) Enter some options.

If the error persists, could you try out the .fig file I have attached.
[dropdown.fig.zip](https://github.com/KlausSchaefers/vue-low-code/files/9876574/dropdown.fig.zip)

The error that you see is still a bug, I will fix it in the next days. It only happens of the dropdown is mis configured.
